/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../app/__root'
import { Route as InterviewRouteRouteImport } from './../app/interview/route'
import { Route as HistoryRouteRouteImport } from './../app/history/route'
import { Route as IndexRouteImport } from './../app/index'
import { Route as HistoryIndexRouteImport } from './../app/history/index'
import { Route as InterviewInterviewIdRouteImport } from './../app/interview/$interviewId'
import { Route as HistoryInterviewIdRouteImport } from './../app/history/$interviewId'
import { Route as ApiTokenRouteImport } from './../app/api/token'
import { Route as ApiInterviewsRouteImport } from './../app/api/interviews'
import { Route as ApiInterviewTokenRouteImport } from './../app/api/interview-token'
import { Route as ApiCsrfTokenRouteImport } from './../app/api/csrf-token'
import { Route as ApiSpeechCoachingAnalyzeRouteImport } from './../app/api/speech-coaching/analyze'
import { Route as ApiQuestionsGenerateRouteImport } from './../app/api/questions/generate'
import { Route as ApiInterviewsIdRouteImport } from './../app/api/interviews/$id'
import { Route as ApiAudioUploadRouteImport } from './../app/api/audio/upload'
import { Route as ApiAudioBatchUploadRouteImport } from './../app/api/audio/batch-upload'
import { Route as ApiInterviewsIdMessagesRouteImport } from './../app/api/interviews/$id/messages'
import { Route as ApiAudioFilesSplatRouteImport } from './../app/api/audio/files/$'

const InterviewRouteRoute = InterviewRouteRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRouteRoute = HistoryRouteRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRouteRoute,
} as any)
const InterviewInterviewIdRoute = InterviewInterviewIdRouteImport.update({
  id: '/$interviewId',
  path: '/$interviewId',
  getParentRoute: () => InterviewRouteRoute,
} as any)
const HistoryInterviewIdRoute = HistoryInterviewIdRouteImport.update({
  id: '/$interviewId',
  path: '/$interviewId',
  getParentRoute: () => HistoryRouteRoute,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewsRoute = ApiInterviewsRouteImport.update({
  id: '/api/interviews',
  path: '/api/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewTokenRoute = ApiInterviewTokenRouteImport.update({
  id: '/api/interview-token',
  path: '/api/interview-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCsrfTokenRoute = ApiCsrfTokenRouteImport.update({
  id: '/api/csrf-token',
  path: '/api/csrf-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechCoachingAnalyzeRoute =
  ApiSpeechCoachingAnalyzeRouteImport.update({
    id: '/api/speech-coaching/analyze',
    path: '/api/speech-coaching/analyze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionsGenerateRoute = ApiQuestionsGenerateRouteImport.update({
  id: '/api/questions/generate',
  path: '/api/questions/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewsIdRoute = ApiInterviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInterviewsRoute,
} as any)
const ApiAudioUploadRoute = ApiAudioUploadRouteImport.update({
  id: '/api/audio/upload',
  path: '/api/audio/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioBatchUploadRoute = ApiAudioBatchUploadRouteImport.update({
  id: '/api/audio/batch-upload',
  path: '/api/audio/batch-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewsIdMessagesRoute = ApiInterviewsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiInterviewsIdRoute,
} as any)
const ApiAudioFilesSplatRoute = ApiAudioFilesSplatRouteImport.update({
  id: '/api/audio/files/$',
  path: '/api/audio/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteRouteWithChildren
  '/interview': typeof InterviewRouteRouteWithChildren
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/interview-token': typeof ApiInterviewTokenRoute
  '/api/interviews': typeof ApiInterviewsRouteWithChildren
  '/api/token': typeof ApiTokenRoute
  '/history/$interviewId': typeof HistoryInterviewIdRoute
  '/interview/$interviewId': typeof InterviewInterviewIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/audio/batch-upload': typeof ApiAudioBatchUploadRoute
  '/api/audio/upload': typeof ApiAudioUploadRoute
  '/api/interviews/$id': typeof ApiInterviewsIdRouteWithChildren
  '/api/questions/generate': typeof ApiQuestionsGenerateRoute
  '/api/speech-coaching/analyze': typeof ApiSpeechCoachingAnalyzeRoute
  '/api/audio/files/$': typeof ApiAudioFilesSplatRoute
  '/api/interviews/$id/messages': typeof ApiInterviewsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interview': typeof InterviewRouteRouteWithChildren
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/interview-token': typeof ApiInterviewTokenRoute
  '/api/interviews': typeof ApiInterviewsRouteWithChildren
  '/api/token': typeof ApiTokenRoute
  '/history/$interviewId': typeof HistoryInterviewIdRoute
  '/interview/$interviewId': typeof InterviewInterviewIdRoute
  '/history': typeof HistoryIndexRoute
  '/api/audio/batch-upload': typeof ApiAudioBatchUploadRoute
  '/api/audio/upload': typeof ApiAudioUploadRoute
  '/api/interviews/$id': typeof ApiInterviewsIdRouteWithChildren
  '/api/questions/generate': typeof ApiQuestionsGenerateRoute
  '/api/speech-coaching/analyze': typeof ApiSpeechCoachingAnalyzeRoute
  '/api/audio/files/$': typeof ApiAudioFilesSplatRoute
  '/api/interviews/$id/messages': typeof ApiInterviewsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteRouteWithChildren
  '/interview': typeof InterviewRouteRouteWithChildren
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/interview-token': typeof ApiInterviewTokenRoute
  '/api/interviews': typeof ApiInterviewsRouteWithChildren
  '/api/token': typeof ApiTokenRoute
  '/history/$interviewId': typeof HistoryInterviewIdRoute
  '/interview/$interviewId': typeof InterviewInterviewIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/audio/batch-upload': typeof ApiAudioBatchUploadRoute
  '/api/audio/upload': typeof ApiAudioUploadRoute
  '/api/interviews/$id': typeof ApiInterviewsIdRouteWithChildren
  '/api/questions/generate': typeof ApiQuestionsGenerateRoute
  '/api/speech-coaching/analyze': typeof ApiSpeechCoachingAnalyzeRoute
  '/api/audio/files/$': typeof ApiAudioFilesSplatRoute
  '/api/interviews/$id/messages': typeof ApiInterviewsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/interview'
    | '/api/csrf-token'
    | '/api/interview-token'
    | '/api/interviews'
    | '/api/token'
    | '/history/$interviewId'
    | '/interview/$interviewId'
    | '/history/'
    | '/api/audio/batch-upload'
    | '/api/audio/upload'
    | '/api/interviews/$id'
    | '/api/questions/generate'
    | '/api/speech-coaching/analyze'
    | '/api/audio/files/$'
    | '/api/interviews/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interview'
    | '/api/csrf-token'
    | '/api/interview-token'
    | '/api/interviews'
    | '/api/token'
    | '/history/$interviewId'
    | '/interview/$interviewId'
    | '/history'
    | '/api/audio/batch-upload'
    | '/api/audio/upload'
    | '/api/interviews/$id'
    | '/api/questions/generate'
    | '/api/speech-coaching/analyze'
    | '/api/audio/files/$'
    | '/api/interviews/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/interview'
    | '/api/csrf-token'
    | '/api/interview-token'
    | '/api/interviews'
    | '/api/token'
    | '/history/$interviewId'
    | '/interview/$interviewId'
    | '/history/'
    | '/api/audio/batch-upload'
    | '/api/audio/upload'
    | '/api/interviews/$id'
    | '/api/questions/generate'
    | '/api/speech-coaching/analyze'
    | '/api/audio/files/$'
    | '/api/interviews/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRouteRoute: typeof HistoryRouteRouteWithChildren
  InterviewRouteRoute: typeof InterviewRouteRouteWithChildren
  ApiCsrfTokenRoute: typeof ApiCsrfTokenRoute
  ApiInterviewTokenRoute: typeof ApiInterviewTokenRoute
  ApiInterviewsRoute: typeof ApiInterviewsRouteWithChildren
  ApiTokenRoute: typeof ApiTokenRoute
  ApiAudioBatchUploadRoute: typeof ApiAudioBatchUploadRoute
  ApiAudioUploadRoute: typeof ApiAudioUploadRoute
  ApiQuestionsGenerateRoute: typeof ApiQuestionsGenerateRoute
  ApiSpeechCoachingAnalyzeRoute: typeof ApiSpeechCoachingAnalyzeRoute
  ApiAudioFilesSplatRoute: typeof ApiAudioFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRouteRoute
    }
    '/interview/$interviewId': {
      id: '/interview/$interviewId'
      path: '/$interviewId'
      fullPath: '/interview/$interviewId'
      preLoaderRoute: typeof InterviewInterviewIdRouteImport
      parentRoute: typeof InterviewRouteRoute
    }
    '/history/$interviewId': {
      id: '/history/$interviewId'
      path: '/$interviewId'
      fullPath: '/history/$interviewId'
      preLoaderRoute: typeof HistoryInterviewIdRouteImport
      parentRoute: typeof HistoryRouteRoute
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interviews': {
      id: '/api/interviews'
      path: '/api/interviews'
      fullPath: '/api/interviews'
      preLoaderRoute: typeof ApiInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-token': {
      id: '/api/interview-token'
      path: '/api/interview-token'
      fullPath: '/api/interview-token'
      preLoaderRoute: typeof ApiInterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csrf-token': {
      id: '/api/csrf-token'
      path: '/api/csrf-token'
      fullPath: '/api/csrf-token'
      preLoaderRoute: typeof ApiCsrfTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech-coaching/analyze': {
      id: '/api/speech-coaching/analyze'
      path: '/api/speech-coaching/analyze'
      fullPath: '/api/speech-coaching/analyze'
      preLoaderRoute: typeof ApiSpeechCoachingAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/generate': {
      id: '/api/questions/generate'
      path: '/api/questions/generate'
      fullPath: '/api/questions/generate'
      preLoaderRoute: typeof ApiQuestionsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interviews/$id': {
      id: '/api/interviews/$id'
      path: '/$id'
      fullPath: '/api/interviews/$id'
      preLoaderRoute: typeof ApiInterviewsIdRouteImport
      parentRoute: typeof ApiInterviewsRoute
    }
    '/api/audio/upload': {
      id: '/api/audio/upload'
      path: '/api/audio/upload'
      fullPath: '/api/audio/upload'
      preLoaderRoute: typeof ApiAudioUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/batch-upload': {
      id: '/api/audio/batch-upload'
      path: '/api/audio/batch-upload'
      fullPath: '/api/audio/batch-upload'
      preLoaderRoute: typeof ApiAudioBatchUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interviews/$id/messages': {
      id: '/api/interviews/$id/messages'
      path: '/messages'
      fullPath: '/api/interviews/$id/messages'
      preLoaderRoute: typeof ApiInterviewsIdMessagesRouteImport
      parentRoute: typeof ApiInterviewsIdRoute
    }
    '/api/audio/files/$': {
      id: '/api/audio/files/$'
      path: '/api/audio/files/$'
      fullPath: '/api/audio/files/$'
      preLoaderRoute: typeof ApiAudioFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteRouteChildren {
  HistoryInterviewIdRoute: typeof HistoryInterviewIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteRouteChildren: HistoryRouteRouteChildren = {
  HistoryInterviewIdRoute: HistoryInterviewIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteRouteWithChildren = HistoryRouteRoute._addFileChildren(
  HistoryRouteRouteChildren,
)

interface InterviewRouteRouteChildren {
  InterviewInterviewIdRoute: typeof InterviewInterviewIdRoute
}

const InterviewRouteRouteChildren: InterviewRouteRouteChildren = {
  InterviewInterviewIdRoute: InterviewInterviewIdRoute,
}

const InterviewRouteRouteWithChildren = InterviewRouteRoute._addFileChildren(
  InterviewRouteRouteChildren,
)

interface ApiInterviewsIdRouteChildren {
  ApiInterviewsIdMessagesRoute: typeof ApiInterviewsIdMessagesRoute
}

const ApiInterviewsIdRouteChildren: ApiInterviewsIdRouteChildren = {
  ApiInterviewsIdMessagesRoute: ApiInterviewsIdMessagesRoute,
}

const ApiInterviewsIdRouteWithChildren = ApiInterviewsIdRoute._addFileChildren(
  ApiInterviewsIdRouteChildren,
)

interface ApiInterviewsRouteChildren {
  ApiInterviewsIdRoute: typeof ApiInterviewsIdRouteWithChildren
}

const ApiInterviewsRouteChildren: ApiInterviewsRouteChildren = {
  ApiInterviewsIdRoute: ApiInterviewsIdRouteWithChildren,
}

const ApiInterviewsRouteWithChildren = ApiInterviewsRoute._addFileChildren(
  ApiInterviewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRouteRoute: HistoryRouteRouteWithChildren,
  InterviewRouteRoute: InterviewRouteRouteWithChildren,
  ApiCsrfTokenRoute: ApiCsrfTokenRoute,
  ApiInterviewTokenRoute: ApiInterviewTokenRoute,
  ApiInterviewsRoute: ApiInterviewsRouteWithChildren,
  ApiTokenRoute: ApiTokenRoute,
  ApiAudioBatchUploadRoute: ApiAudioBatchUploadRoute,
  ApiAudioUploadRoute: ApiAudioUploadRoute,
  ApiQuestionsGenerateRoute: ApiQuestionsGenerateRoute,
  ApiSpeechCoachingAnalyzeRoute: ApiSpeechCoachingAnalyzeRoute,
  ApiAudioFilesSplatRoute: ApiAudioFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
